version: "3.7"
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
#    restart: always
    secrets:
      - secret_token
    environment:
      - bot_token=/run/secrets/secret_token
secrets:
  secret_token:
    file: src/token.txt
